# Added a Secret block for wordpress secret 
apiVersion: v1
kind: Secret
metadata:
  name: wp-mysql-pass
  namespace: company-blog
  labels:
    app: wp-blog
type: Opaque
# This could easily be base64 encoded as well, or better still read in from an external source 
# like hashicorp's vault, AWS secretsmanager etc 
stringData:
  mysqldatabase: mysql
  mysqluser: mysql
  mysqlpassword: igbogbobombers
---
# Adding a Persistent Volume to be used by the PVC 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv
  namespace: company-blog
  labels:
    app: wp-blog
spec:
  storageClassName: ""
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/hostpath-provisioner"
---
# Updated with a storageClassName to match the Persistent Volume 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pv-claim
  namespace: company-blog
  labels:
    app: wp-blog
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: company-blog
  labels:
    app: wp-blog
spec:
  ports:
    - port: 80
  selector:
    app: wp-blog
    tier: frontend
  type: LoadBalancer
---
# TODO: complete the wordpress deployment
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: wordpress
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: company-blog
  labels:
    app: wp-blog
spec:
  ports:
  - name: web
    port: 80
  selector:
    app: wp-blog
---
# Deployment for the wordpress service 
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wp-blog
  name: wordpress
  namespace: company-blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: wordpress:latest
        name: wordpress
        ports:
        - containerPort: 80
          name: web
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 300
          periodSeconds: 10
        env:
        - name: WORDPRESS_DB_HOST
          value: wordpress-mysql:3306
        - name: WORDPRESS_DB_NAME
          valueFrom:
            secretKeyRef:
              name: wp-mysql-pass
              key: mysqldatabase
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: wp-mysql-pass
              key: mysqluser
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wp-mysql-pass
              key: mysqlpassword
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wordpress-pv-claim