apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: code-challenge
  labels:
    app: wp-blog
spec:
  ports:
    - port: 80
  selector:
    app: wp-blog
    tier: frontend
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  namespace: code-challenge
  labels:
    app: wp-blog
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
# TODO: complete the wordpress deployment
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: wordpress

